# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Surveys' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Surveys
  pod 'SwiftLint'
  pod 'Alamofire', '~> 5.4'
  pod 'SnapKit', '~> 5.0.0'
  pod 'KeychainAccess', '~> 4.2'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxSwiftExt/Core'
  pod 'RxDataSources', '~> 4.0.1'

  target 'SurveysTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SurveysUITests' do
    # Pods for testing
  end

end
